### ISSUE TITLE
Image link shortcuts overlapping post text

### ISSUE THREAD

**Issue by Zak8022** [hariettem/Artemis#207]
**Describe the bug**
The image links in the referenced thread are overlapping with the actual post text. I suspect this is because the post has many links, and something isn't ready to handle that many separate links.

**To Reproduce**
1. Go to this thread: https://kbin.social/m/kbinMeta/t/145540/I-m-back-with-several-more-community-icons-check-out-Artemis
2. Scroll down not very far to see 

**Expected behavior**
I expect to see all of the original post text _before_ any of the image links. The image links should all be listed at the bottom of the post text, probably before the post details (like upvote count, boost count, thread age).

**Screenshots**
Screenshot 1, showing the top of the post. You can see the first 4 links overlapping the post text.
![IMG_187824B2B5D8-1](https://github.com/hariettem/Artemis/assets/13437686/ac138000-064e-46b5-abbc-8dca67335cea)

Screenshot 1, showing the bottom of the post. You can see the last few links also/still overlapping the post text.
![IMG_5F9CE34E2D04-1](https://github.com/hariettem/Artemis/assets/13437686/ca3fff0a-645c-4f8f-8696-3765d5685278)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1
 - Version 0.1.5

**Additional context**
Additional posts that are exhibiting similar overlapping issues:
https://kbin.social/m/steamdeck@sopuli.xyz/t/147319/shared-on-Artemis
https://kbin.social/m/fediverse/t/145147/shared-on-Artemis - This one doesn't even have any image links, but the post text still overlaps with the post details (might be a separate issue, not sure).
https://kbin.social/m/Diablo/t/147936/shared-on-Artemis - another with no image links, but post text is still overlapped.

Edit: added links to additional posts exhibiting similar overlapping issues.

Edit 2: I think this has less to do with the link shortcuts and more to do with the length of the post itself.

**Comment by hiimmike** [comment]
Wanted to confirm this is happening on iPhone XS iOS 16.5.1, app version 0.1.5.

https://imgur.com/a/C5w5IN9

**Comment by pvmzqahgyd** [comment]
**Below are all related to interface overlaps**

https://github.com/hariettem/Artemis/issues/213
https://github.com/hariettem/Artemis/issues/207
https://github.com/hariettem/Artemis/issues/181
https://github.com/hariettem/Artemis/issues/226
https://github.com/hariettem/Artemis/issues/181
https://github.com/hariettem/Artemis/issues/170

**Comment by hariettem** [comment]
should be fixed with 0.1.7. pls open otherwise

**Comment by pvmzqahgyd** [comment]
Unfortunately still an issue on 0.1.7 / 2307.11.01.55

**Comment by plscks** [comment]
Can confirm this is still happening on v0.1.7 u2307.12.01.18 on iPhone 13 mini iOS 16.6 public beta (20G5058d).
