### ISSUE TITLE
Layout overflow 

### ISSUE THREAD

**Issue by arian81** [hariettem/Artemis#213]
**Describe the bug**
I came across this post that has overflown text.

**To Reproduce**
1. Go to [this](https://kbin.social/m/android@lemmy.world/t/149356/shared-on-Artemis)

**Expected behavior**
The text to go as long as needed and the user scrolls to see the whole post.

**Screenshots**
![IMG_9089](https://github.com/hariettem/Artemis/assets/35879206/769c7140-03b2-47e7-a44a-fc61486f90ac)

**Comment by ZeroZeroOne-dev** [comment]
Another example: https://kbin.social/m/destiny@lemmy.world/t/147429/shared-on-Artemis

https://github.com/hariettem/Artemis/assets/254635/22a934eb-0272-4dcb-953a-e42c8bf489af

**Comment by Alaric323** [comment]
Yep, just started having this myself on Android.  Image attached.![Screenshot_20230707_162907_Artemis.jpg](https://github.com/hariettem/Artemis/assets/4038592/82df3613-5f7b-4f32-af51-95ca04bc09e2)

**Comment by pvmzqahgyd** [comment]
**Below are all related to interface overlaps**

https://github.com/hariettem/Artemis/issues/213
https://github.com/hariettem/Artemis/issues/207
https://github.com/hariettem/Artemis/issues/181
https://github.com/hariettem/Artemis/issues/226
https://github.com/hariettem/Artemis/issues/181
https://github.com/hariettem/Artemis/issues/170

**Comment by hariettem** [comment]
should be fixed with 0.1.7. reopen otherwise

**Comment by ZeroZeroOne-dev** [comment]
Still happens for me

![IMG_5913](https://github.com/hariettem/Artemis/assets/254635/2ca63114-1331-4703-8f9a-1a12ee99f31f)
![IMG_5912](https://github.com/hariettem/Artemis/assets/254635/ceb37621-edb0-4755-b022-9c5fac87a957)

On 0.1.7 - 2307.09.19.39

Restarted app and reloaded post
