### ISSUE TITLE
Double tap + drag to zoom images closes image viewer instead of zooming

### ISSUE THREAD

**Issue by stephen304** [hariettem/Artemis#317]
**Describe the bug**
In many apps when viewing an image in full screen, you can double tap + drag to zoom the image. I'm not sure if this is a bug or a feature request but when I try to tap twice, holding down on the second tap, then drag my finger down, it seems to close the image viewer instead of zooming because of the first tap.

In other apps I'm used to, tapping once outside the image closes the viewer, but tapping the image itself once does nothing, allowing the double tap + drag to zoom instead of the viewer closing after the first tap

**To Reproduce**
1. Open an image
2. Tap twice, holding on the second tap, then drag downward
3. Image closes instead of zooming

Also:
1. Open an image
2. Tap on the image
3. It closes

**Expected behavior**
I hoped that double tap + drag would allow me to zoom in on images with a single finger, so I don't need to use 2 hands to zoom

**Screenshots**
-N/A-

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12 Lineage 19
 - Version 0.1.7 Update 2307.15.20.44 preview

**Additional context**

**Comment by Daleeburg** [comment]
May be related to #309

**Comment by hariettem** [comment]
fixed

**Comment by stephen304** [comment]
@hariettem This seems to still not work in 0.2.0 update 2308.05.02.02

To be clear, double tap to zoom does work, but that zooms in a fixed amount. The only way to zoom to a custom zoom level is to use 2 fingers and pinch. Pretty much all other reddit/lemmy apps support double tapping with a single finger, holding, then dragging which allows you to smoothly zoom to any amount with a single finger. It's very helpful for single hand usage and accessibility.

**Comment by stephen304** [comment]
Here is a video to help show how it works in Artemis compared to redreader, infinity, and sync. It looks like redreader's implementation doesn't allow one finger zooming into specific parts of the image, but infinity and sync (and the official reddit app) have similar implementations that allow double tap + drag to zoom in a variable amount to any specific part of the image with a single finger.

https://github.com/hariettem/Artemis/assets/981915/51969a0a-cf61-486c-a41f-46294a686329
